name: Export DynamoDB to S3
on:
  schedule:
   - cron: '* * * * *' # Run every day at 2:00 AM UTC
jobs:
  export-dynamodb-to-s3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Replace with your region
      - name: Create DynamoDB table
        run: |
          aws dynamodb create-table \
            --table-name my-receevetable \
            --attribute-definitions AttributeName=id,AttributeType=S \
            --key-schema AttributeName=id,KeyType=HASH \
            --billing-mode PAY_PER_REQUEST \
            --region us-east-1 # Replace with your region
      - name: Create S3 bucket
        run: |
          aws s3api create-bucket \
            --bucket my-receevebucket \
            --region us-east-1 \
            --create-bucket-configuration LocationConstraint=us-east-1 # Replace with your region
      - name: Export DynamoDB to S3
        run: |
          aws dynamodb scan \
            --table-name my-table \
            --select ALL_ATTRIBUTES \
            --output json | \
          aws s3 cp - s3://my-bucket/data.json

