name: Export DynamoDB S3

on:
  schedule:
    - cron: "* * * * *"

jobs:
  export-to-s3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16
      
      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region $AWS_REGION
      
      - name: Create S3 bucket
        run: |
          aws s3api create-bucket --bucket my-bucket --region $AWS_REGION --create-bucket-configuration LocationConstraint=$AWS_REGION
      
      - name: Create DynamoDB table
        run: |
          aws dynamodb create-table --table-name my-table --attribute-definitions AttributeName=Id,AttributeType=S --key-schema AttributeName=Id,KeyType=HASH --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5
      
      - name: Export DynamoDB table to S3
        run: |
          aws dynamodb export-table-to-point-in-time --table-name my-table --s3-bucket my-bucket --s3-prefix my-prefix
