name: Deploy Resources

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create CloudFormation stack
        run: aws cloudformation create-stack --stack-name my-stack --template-body file://cloudformation.yml --capabilities CAPABILITY_NAMED_IAM

      - name: Wait for CloudFormation stack to complete
        run: aws cloudformation wait stack-create-complete --stack-name my-stack

      - name: Display CloudFormation stack resources
        run: aws cloudformation describe-stack-resources --stack-name my-stack
